version: '2'

services:
  confluence:
    image: q2digger/confluence:latest
    container_name: confluence
    hostname: confluence
    volumes:
      - app_data:/var/atlassian/application-data/confluence
    restart: always
    ports:
      - 8090:8090
      - 8091:8091
    networks:
      - confluence
      - proxy
    environment:
      JVM_MINIMUM_MEMORY: "2048m"
      JVM_MAXIMUM_MEMORY: "4096m"
      CATALINA_CONNECTOR_PROXYNAME: "${VIRTUAL_HOST}"
      CATALINA_CONNECTOR_PROXYPORT: "443"
      CATALINA_CONNECTOR_SCHEME: "https"
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VIRTUAL_PORT: "8090"
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - ./synchrony.conf:/etc/nginx/vhost.d/${VIRTUAL_HOST}:ro
      - /var/run/docker.sock:/tmp/docker.sock
      - ./certs/:/etc/nginx/certs:ro
    networks:
      - proxy
  database:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_INITDB_ARGS=--encoding=UNICODE --lc-collate=C --lc-ctype=C
    networks:
      - confluence

volumes:
  db_data:
  app_data:

networks:
  confluence:
  proxy:
